#@ load("@ytt:data", "data")

#@ def version(n):
#@   if n == "develop":
#@     return "0.0.0+develop"
#@   else:
#@     return n
#@   end
#@ end

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ "{}.{}.{}".format(data.values.package.name, data.values.package.domain, version(data.values.package.version))
  namespace: kapp-controller-packaging-global
spec:
  refName: #@ "{}.{}".format(data.values.package.name, data.values.package.domain)
  version: #@ version(data.values.package.version)
#!  releaseNotes: "Fixed some bugs"
#!  capacityRequirementsDescription: "RAM: 10GB"
#!  licenses:
#!  - "Apache 2.0"
#!  releasedAt: 2021-05-05T18:57:06Z
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: #@ "{}/{}-package:{}".format(data.values.registry, data.values.package.name, data.values.package.version)
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp:
            rawOptions: ["--wait-timeout=5m"]